### ISSUE TITLE
[Feature] Upgrade to proper frontend

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#20]
Need a nicer UW theme front-end to replace Streamlit. Ask @amegahed for help. There are a few options:

1. Use CSS in Streamlit to make it looks more official
2. Rewrite with `flask` or `fastapi`

(1) is more favorable for future, e.g., new streamlit project can have a very nice UW theme.

**Comment by JasonLo** [comment]
@amegahed, see [demo](https://huggingface.co/spaces/mbialo/community-search) for reference.

**Comment by JasonLo** [comment]
Example embed jinja

```html
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{bar_plot.title}}</h5>
    <div id="container">
      <div id="vis"></div>
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
<script type="text/javascript">
  var spec = {{bar_plot.spec|safe}};
  var widthOffset = {{bar_plot.width_offset|int}};

  function drawPlot() {
    visWidth = document.getElementById('container').clientWidth;
    vegaEmbed("#vis", spec, { theme: "dark", actions: false, width: visWidth - widthOffset})
    .then(function (result) {})
    .catch(console.error);
  }

  drawPlot();
  window.addEventListener("resize", drawPlot);
</script>

```

**Comment by JasonLo** [comment]
From @amegahed 
Drafted front-end with `flask`
https://github.com/UW-Madison-DSI/uw-community-search

**Comment by JasonLo** [comment]
Can you also an PDF file upload option in the front-end?

**Comment by JasonLo** [comment]
Hi @amegahed 

I had upgraded the back-end locally, but haven't deploy it yet. But this is the API endpoint schema for your reference:

POST: /search_author/
Request body: 
```
{"query": "some string", "top_k": 3}
```
Response body: 

```
[
  {
    "id": "string",  # academicanalytics's id
    "first_name": "string",
    "last_name": "string",
    "community_name": "string",  # Not in use currently
    "score": 0
  }
]
```
I will deploy it somewhere tomorrow.

**Comment by amegahed** [comment]
Ok, super.   Let's try to talk tomorrow about how to integrate both the API and the visual elements.
