### ISSUE TITLE
[Frontend] Tweaking

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#26]
- [x] The text box for search should probably be bigger to indicate one might add a paragraph of text. Maybe have some grey hint text in there to let user know it’s not just keywords

**Comment by amegahed** [comment]
I changed the text box to a resizable textarea field and added some placeholder text.

![Community Search Text](https://github.com/UW-Madison-DSI/community-search/assets/8449604/98046fcf-9df1-4fdb-82f8-71d3bf106ddc)

**Comment by JasonLo** [comment]
Relaying Kyle's comment:

> Coolio. Not sure the search and clear buttons work visually like that though. In something like chat GPT the box grows as you type I think. That’s probably a good model.

- [ ] box grows as you type

**Comment by amegahed** [comment]
Sure, I can make it more chatgpt like where it grows as you type and the search button lies within the text box.

**Comment by JasonLo** [comment]
Small UI tweaking is completed.
