### ISSUE TITLE
[Question] Multi repos or just one?

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#30]
Hi @amegahed,

I noticed you've been active on the frontend repo. Didn't we talk about continuing development on the main `community-search` repo for simpler CI implementation?

That said, if it's more convenient for you to work on the frontend repo, I can arrange a script to synchronize the code during each deployment. What's your preference? a) Keep them separate or b) Merge them.

**Comment by amegahed** [comment]
Can we just merge into a single branch?

**Comment by JasonLo** [comment]
Yes, you can clone this repo `UW-Madison-DSI/community-search` and continue your work from here.
