### ISSUE TITLE
[Problem] Searching for oneself often does not yield the anticipated results.

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#34]
Problem: 

- Users often search for themselves, expecting to find results about themselves. However, the current system's design (weighted publication search) might not display the user in the search results.

Example:
- URL input: https://pages.cs.wisc.edu/~jerryzhu/research.html
- Return: Not Jerry.

Plausible solution:

- [x] #36
- [x] #32

**Comment by amegahed** [comment]
Would you like to add a FAQ page to the application / top nav bar for questions such as this?    

It seems that we should keep the "Help" page relatively simple and focused on the application functionality / UI whereas there are a range of questions about how the data is sourced and processed that would be better of on a separate page.

**Comment by JasonLo** [comment]
I slightly prefer FAQ as a separate section (top level menu item) for easier access. 
Both will works I guess.

**Comment by JasonLo** [comment]
Update sorting algorithm in d4cb4e291dcfcdff076be05d56144d8ee7b94ffd 

Now, with the input text obtained from Jerry's site as search string: 

> What if there is a teacher who knows the learning goal (such as a target model) and wants to design the optimal (such as the smallest) training data for a learner? This is the question of designing the best "lesson," and the inverse problem of machine learning. Machine teaching has obvious applications in education and cognitive psychology, as well as potential applications in computer security. The optimal training set is usually not an i.i.d. sample, but rather requires combinatorial search. Finding the optimal training set is in general a difficult bilevel optimization problem, though in certain cases there are tractable solutions. 

We can obtain this list of results

1. Zhu, Jerry
2. Nowak, Robert
3. Mcdaniel, Patrick
4. Nathan, Mitchell
5. Craven, Mark

**Comment by JasonLo** [comment]
Jerry case is working now.
