### ISSUE TITLE
Implement a new search entry point that utilizes names as input.

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#36]

**Comment by JasonLo** [comment]
Hi @amegahed, `get_author` API route is pushed to prod. 

http://35.209.217.139:8765/docs#/default/get_author_get_author__post

Can add a new search option in the front-end, which takes `first_name` and `last_name` as inputs, and dump the entire `json` as output for now.

**Comment by JasonLo** [comment]
Force user to input <first name> <last name>

**Comment by JasonLo** [comment]
Bug:

Input: Jerry Zhu

Output:

![Image](https://github.com/UW-Madison-DSI/community-search/assets/1927986/e9217596-718b-4c69-b2cd-3f6139ee9a47)

**Comment by JasonLo** [comment]
Also please add the help text in the input box with something like: Input the name with this format: first_name last_name.

**Comment by amegahed** [comment]
This was fixed in the previous commit (about 15 mins ago).

**Comment by amegahed** [comment]
Added "Firstname Lastname" placeholder text for search by name.
