### ISSUE TITLE
[Frontend] Dark/Light theme

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#51]
Not urgent, but nice to have matching theme, especially for the plot.

**Comment by amegahed** [comment]
![Dark Mode Plot](https://github.com/UW-Madison-DSI/community-search/assets/8449604/50449214-183f-4e26-9994-a18887c878b7)

**Comment by JasonLo** [comment]
Look cool~

**Comment by JasonLo** [comment]
The plot remains in dark mode despite the global setting being in light mode.
