### ISSUE TITLE
Update the format of name search results to align with other search types.

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#64]
- [x] Return format match with other search types
- [x] Include an additional link in each author result that directs users to the internal author page (currently return of `get_author`)

From Kyle:

> It’s not super obvious that name search would return something totally different. Maybe that different type of return result should be a in the advanced options.
Having a search by name that shows gives the same list view like result with links to academic analytics makes sense to me. Maybe under that is where the list of papers could go.

**Comment by JasonLo** [comment]
I don't see the changes in the live site.

**Comment by amegahed** [comment]
I'm seeing the change in GitHub but not on the live site.   Did the deployment fail, perhaps?
