### ISSUE TITLE
Update Search by PDF description

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#79]
The PDF search says:

>  Search By PDF
> Drag and drop or select a PDF file to search for the contents of this file.

[9:50](https://uwmadison-dsi.slack.com/archives/C05M27PS3SA/p1693579853373499)

suggest minor change:

> Search By PDF
> Drag and drop or select a PDF file to perform a search based on the contents of this file.

**Comment by amegahed** [comment]
Thanks.   Yes, I thought that the original the text for this was awkward.   Note:   I've moved the various notification and error messages into the defaults.json file so if we need to wordsmith the text in the future, it will be easier.
