### ISSUE TITLE
minor text changes

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/community-search#82]
- [ ] On main panel: This repository indexes papers written by faculty, sourced from academic analytics, and notes that the collection may not be comprehensive.
- [ ] URL search hint: Enter a URL. The search will be based on the contents of this webpage.
- [ ] Text search hint: Enter a search terms or text (can be sentences or entire paragraphs)

I’m thinking a bit more about explanatory text that go in the main panel on the landing page.
[10:54](https://uwmadison-dsi.slack.com/archives/C05M27PS3SA/p1693583654725309)
For instance, we might want to say something about it indexing the papers written by faculty. The about section should definitely say something about that to make it clear that the source of the papers is academic analytics and that it might not be complete.
[10:57](https://uwmadison-dsi.slack.com/archives/C05M27PS3SA/p1693583830156229)
when in URL mode, the hint text in the search bar says
 Search terms or text
Should probably be
 Enter a URL. The search will be based on the contents of this webpage.
[11:00](https://uwmadison-dsi.slack.com/archives/C05M27PS3SA/p1693584003191089)
and in text search mode
 Search terms or text
might be
 Enter a search terms or text (can be sentences or entire paragraphs)

**Comment by amegahed** [comment]
For the explanatory text, I added that to the search results view rather than to the main view because I thought it should be visible alongside the results.
